global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "load_balancer"
    static_configs:
      - targets: ["load-balancer.up.railway.app:8080"] # Docker service name + port
        labels:
          service: "loadbalancer"
